"""empty message

Revision ID: 740472a87f5b
Revises: e95d0e5c0bad
Create Date: 2020-08-04 17:08:59.490664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740472a87f5b'
down_revision = 'e95d0e5c0bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # set default value to featured column
    op.execute('ALTER TABLE promotions ALTER COLUMN featured SET DEFAULT false;')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    # ### end Alembic commands ###
